/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as RecordRouteImport } from './routes/record'
import { Route as ApiPublicExportRouteImport } from './routes/api/public/export'
import { Route as ApiPublicWeatherRouteImport } from './routes/api/public/weather'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExportRoute = ApiPublicExportRouteImport.update({
  id: '/api/public/export',
  path: '/api/public/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWeatherRoute = ApiPublicWeatherRouteImport.update({
  id: '/api/public/weather',
  path: '/api/public/weather',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/plan': typeof PlanRoute
  '/record': typeof RecordRoute
  '/api/public/export': typeof ApiPublicExportRoute
  '/api/public/weather': typeof ApiPublicWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/plan': typeof PlanRoute
  '/record': typeof RecordRoute
  '/api/public/export': typeof ApiPublicExportRoute
  '/api/public/weather': typeof ApiPublicWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/plan': typeof PlanRoute
  '/record': typeof RecordRoute
  '/api/public/export': typeof ApiPublicExportRoute
  '/api/public/weather': typeof ApiPublicWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goals'
    | '/history'
    | '/plan'
    | '/record'
    | '/api/public/export'
    | '/api/public/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/goals'
    | '/history'
    | '/plan'
    | '/record'
    | '/api/public/export'
    | '/api/public/weather'
  id:
    | '__root__'
    | '/'
    | '/goals'
    | '/history'
    | '/plan'
    | '/record'
    | '/api/public/export'
    | '/api/public/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoalsRoute: typeof GoalsRoute
  HistoryRoute: typeof HistoryRoute
  PlanRoute: typeof PlanRoute
  RecordRoute: typeof RecordRoute
  ApiPublicExportRoute: typeof ApiPublicExportRoute
  ApiPublicWeatherRoute: typeof ApiPublicWeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/export': {
      id: '/api/public/export'
      path: '/api/public/export'
      fullPath: '/api/public/export'
      preLoaderRoute: typeof ApiPublicExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/weather': {
      id: '/api/public/weather'
      path: '/api/public/weather'
      fullPath: '/api/public/weather'
      preLoaderRoute: typeof ApiPublicWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoalsRoute: GoalsRoute,
  HistoryRoute: HistoryRoute,
  PlanRoute: PlanRoute,
  RecordRoute: RecordRoute,
  ApiPublicExportRoute: ApiPublicExportRoute,
  ApiPublicWeatherRoute: ApiPublicWeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
